apiVersion: v1
kind: Service
metadata:
  name: email-microservice
  labels:
    app: email-microservice
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: email-microservice
  type: LoadBalancer
